/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.infoeducatie.app.client.entities;

public class Contestant {
	private Integer id;

 	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	private String name;

 	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

}