/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.infoeducatie.app.client.entities;

public class Edition {
	private String registration_end_date;

 	public void setRegistration_end_date(String registration_end_date) {
		this.registration_end_date = registration_end_date;
	}

	public String getRegistration_end_date() {
		return registration_end_date;
	}

	private String motto;

 	public void setMotto(String motto) {
		this.motto = motto;
	}

	public String getMotto() {
		return motto;
	}

	private Integer year;

 	public void setYear(Integer year) {
		this.year = year;
	}

	public Integer getYear() {
		return year;
	}

	private String travel_data_deadline;

 	public void setTravel_data_deadline(String travel_data_deadline) {
		this.travel_data_deadline = travel_data_deadline;
	}

	public String getTravel_data_deadline() {
		return travel_data_deadline;
	}

	private Integer id;

 	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	private Integer projects_count;

 	public void setProjects_count(Integer projects_count) {
		this.projects_count = projects_count;
	}

	public Integer getProjects_count() {
		return projects_count;
	}

	private Integer contestants_count;

 	public void setContestants_count(Integer contestants_count) {
		this.contestants_count = contestants_count;
	}

	public Integer getContestants_count() {
		return contestants_count;
	}

	private String registration_start_date;

 	public void setRegistration_start_date(String registration_start_date) {
		this.registration_start_date = registration_start_date;
	}

	public String getRegistration_start_date() {
		return registration_start_date;
	}

	private Integer count;

 	public void setCount(Integer count) {
		this.count = count;
	}

	public Integer getCount() {
		return count;
	}

	private String name;

 	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	private Integer counties_count;

 	public void setCounties_count(Integer counties_count) {
		this.counties_count = counties_count;
	}

	public Integer getCounties_count() {
		return counties_count;
	}

}