/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.infoeducatie.app.client.entities;

public class Project {
	private String discourse_url;

 	public void setDiscourse_url(String discourse_url) {
		this.discourse_url = discourse_url;
	}

	public String getDiscourse_url() {
		return discourse_url;
	}

	private Integer discourse_comments_count;

 	public void setDiscourse_comments_count(Integer discourse_comments_count) {
		this.discourse_comments_count = discourse_comments_count;
	}

	public Integer getDiscourse_comments_count() {
		return discourse_comments_count;
	}

	private Contestant[] contestants;

 	public void setContestants(Contestant[] contestants) {
		this.contestants = contestants;
	}

	public Contestant[] getContestants() {
		return contestants;
	}

	private String homepage;

 	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	public String getHomepage() {
		return homepage;
	}

	private String technical_description;

 	public void setTechnical_description(String technical_description) {
		this.technical_description = technical_description;
	}

	public String getTechnical_description() {
		return technical_description;
	}

	private Screenshot[] screenshots;

 	public void setScreenshots(Screenshot[] screenshots) {
		this.screenshots = screenshots;
	}

	public Screenshot[] getScreenshots() {
		return screenshots;
	}

	private Integer id;

 	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	private String category;

 	public void setCategory(String category) {
		this.category = category;
	}

	public String getCategory() {
		return category;
	}

	private String title;

 	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitle() {
		return title;
	}

	private String system_requirements;

 	public void setSystem_requirements(String system_requirements) {
		this.system_requirements = system_requirements;
	}

	public String getSystem_requirements() {
		return system_requirements;
	}

	private String county;

 	public void setCounty(String county) {
		this.county = county;
	}

	public String getCounty() {
		return county;
	}

	private String source_url;

 	public void setSource_url(String source_url) {
		this.source_url = source_url;
	}

	public String getSource_url() {
		return source_url;
	}

	private String description;

 	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return description;
	}

}