/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.infoeducatie.app.client.entities;

public class Screenshot {
	private String url;

 	public void setUrl(String url) {
		this.url = url;
	}

	public String getUrl() {
		return url;
	}

}